### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jkhamilton** [zrubinstein/sds192-mp2#3]
Still getting this error. I think one of you said you fixed it at the end of class but what did you do? Could you commit and push the latest/fixed version

![screen shot 2017-03-24 at 1 54 43 pm](https://cloud.githubusercontent.com/assets/26280586/24307018/fd08d024-1098-11e7-916a-5bad6c120bd4.png)

**Comment by jaatin** [comment]
Fixed, sorry, I forgot to change one of the variable names back!
